/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuditLog {
  action: string;
  changed_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  new_values: Json | null;
  old_values: Json | null;
  user_id: string | null;
}

export interface Budgets {
  amount_limit: string | null;
  category_id: Int8 | null;
  created_at: Generated<Timestamp>;
  effective_from: string;
  id: Generated<Int8>;
  scope: string;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Categories {
  category_group_id: Int8 | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  name: string;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface CategoryGroups {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PrivacyRequests {
  completed_at: Timestamp | null;
  id: Generated<Int8>;
  note: string | null;
  requested_at: Generated<Timestamp>;
  status: Generated<string>;
  type: string;
  user_id: string;
}

export interface RecurringTransactions {
  amount: string;
  category_id: Int8;
  created_at: Generated<Timestamp>;
  description: string | null;
  end_date: string | null;
  id: Generated<Int8>;
  interval_count: Generated<number>;
  interval_unit: string;
  is_active: Generated<boolean>;
  name: string;
  next_due_date: string;
  start_date: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface Transactions {
  amount: string;
  category_id: Int8;
  client_uuid: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<Int8>;
  name: string;
  payment_date: string;
  planned_amount: string | null;
  recurring_due_date: string | null;
  recurring_transaction_id: Int8 | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserConsents {
  granted_at: Generated<Timestamp>;
  id: Generated<Int8>;
  policy_version: string;
  purpose: string;
  user_id: string;
  withdrawn_at: Timestamp | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deletion_requested_at: Timestamp | null;
  email: string;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  image: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface UserSettings {
  created_at: Generated<Timestamp>;
  currency: string;
  locale: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Verifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  accounts: Accounts;
  audit_log: AuditLog;
  budgets: Budgets;
  categories: Categories;
  category_groups: CategoryGroups;
  privacy_requests: PrivacyRequests;
  recurring_transactions: RecurringTransactions;
  sessions: Sessions;
  transactions: Transactions;
  user_consents: UserConsents;
  user_settings: UserSettings;
  users: Users;
  verifications: Verifications;
}
