-- Up Migration
-- Auth tables match better-auth 1.7.7 with generateId uuid and snake_case fields.
-- String columns keep the varchar limits from the schema file. Better Auth treats varchar as text.

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(100) NOT NULL,
  email varchar(254) NOT NULL,
  email_verified boolean NOT NULL DEFAULT false,
  image text,
  deletion_requested_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_uidx ON users (email);
CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));

CREATE TABLE sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token text NOT NULL,
  expires_at timestamptz NOT NULL,
  ip_address text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX sessions_token_uidx ON sessions (token);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX idx_sessions_expiry ON sessions (expires_at);

CREATE TABLE accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  provider_id varchar(50) NOT NULL,
  account_id varchar(255) NOT NULL,
  password text,
  access_token text,
  refresh_token text,
  id_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  scope text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_accounts_provider_subject ON accounts (provider_id, account_id);
CREATE INDEX accounts_user_id_idx ON accounts (user_id);

CREATE TABLE verifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier text NOT NULL,
  value text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX verifications_identifier_idx ON verifications (identifier);
CREATE INDEX idx_verifications_expiry ON verifications (expires_at);

CREATE TABLE user_settings (
  user_id uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  currency char(3) NOT NULL,
  locale varchar(35) NOT NULL DEFAULT 'en',
  timezone varchar(64) NOT NULL DEFAULT 'UTC',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_consents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  purpose varchar(40) NOT NULL,
  policy_version varchar(20) NOT NULL,
  granted_at timestamptz NOT NULL DEFAULT now(),
  withdrawn_at timestamptz
);

CREATE INDEX idx_consents_user_purpose ON user_consents (user_id, purpose, granted_at DESC);

CREATE TABLE privacy_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  type varchar(20) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'PENDING',
  requested_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  note varchar(255)
);

CREATE INDEX idx_privacy_requests_user ON privacy_requests (user_id, requested_at DESC);

CREATE TABLE category_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name varchar(50) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_user_group_name ON category_groups (user_id, name);

CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_group_id bigint REFERENCES category_groups (id) ON DELETE SET NULL,
  type varchar(10) NOT NULL,
  name varchar(50) NOT NULL,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_categories_id_user ON categories (id, user_id);
CREATE UNIQUE INDEX uq_categories_id_user_type ON categories (id, user_id, type);
CREATE INDEX idx_categories_user_active ON categories (user_id, deleted_at);
CREATE INDEX idx_categories_group ON categories (category_group_id);

CREATE TABLE budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type varchar(10) NOT NULL,
  scope varchar(10) NOT NULL,
  category_id bigint,
  amount_limit numeric(12, 2),
  effective_from date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_budget_category_month ON budgets (user_id, category_id, effective_from);
CREATE INDEX idx_budget_lookup ON budgets (user_id, type, scope, category_id, effective_from);
CREATE INDEX idx_budgets_category ON budgets (category_id);

ALTER TABLE budgets
  ADD CONSTRAINT fk_budgets_category_type
  FOREIGN KEY (category_id, user_id, type)
  REFERENCES categories (id, user_id, type)
  ON DELETE CASCADE;

CREATE TABLE recurring_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_id bigint NOT NULL,
  name varchar(50) NOT NULL,
  description varchar(255),
  amount numeric(12, 2) NOT NULL,
  start_date date NOT NULL,
  interval_unit varchar(10) NOT NULL,
  interval_count smallint NOT NULL DEFAULT 1,
  next_due_date date NOT NULL,
  end_date date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_recurring_due ON recurring_transactions (is_active, next_due_date);
CREATE INDEX idx_recurring_user_due ON recurring_transactions (user_id, is_active, next_due_date);
CREATE INDEX idx_recurring_category ON recurring_transactions (category_id);

ALTER TABLE recurring_transactions
  ADD CONSTRAINT fk_recurring_category
  FOREIGN KEY (category_id, user_id)
  REFERENCES categories (id, user_id)
  ON DELETE NO ACTION;

CREATE TABLE transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_id bigint NOT NULL,
  recurring_transaction_id bigint REFERENCES recurring_transactions (id) ON DELETE SET NULL,
  recurring_due_date date,
  client_uuid uuid,
  name varchar(50) NOT NULL,
  amount numeric(12, 2) NOT NULL,
  planned_amount numeric(12, 2),
  payment_date date NOT NULL,
  description varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_tx_user_date ON transactions (user_id, payment_date DESC);
CREATE INDEX idx_tx_user_category_date ON transactions (user_id, category_id, payment_date DESC);
CREATE INDEX idx_tx_category ON transactions (category_id);
CREATE UNIQUE INDEX uq_tx_recurring_occurrence ON transactions (recurring_transaction_id, recurring_due_date);
CREATE UNIQUE INDEX uq_tx_client_uuid ON transactions (user_id, client_uuid);

ALTER TABLE transactions
  ADD CONSTRAINT fk_tx_category
  FOREIGN KEY (category_id, user_id)
  REFERENCES categories (id, user_id)
  ON DELETE NO ACTION;

CREATE TABLE audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid,
  entity_type varchar(50) NOT NULL,
  entity_id varchar(64) NOT NULL,
  action varchar(10) NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_user_time ON audit_log (user_id, changed_at DESC);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id, changed_at DESC);

-- Down Migration

DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS recurring_transactions CASCADE;
DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS category_groups CASCADE;
DROP TABLE IF EXISTS privacy_requests CASCADE;
DROP TABLE IF EXISTS user_consents CASCADE;
DROP TABLE IF EXISTS user_settings CASCADE;
DROP TABLE IF EXISTS verifications CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
