name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK and cache
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'maven'

      - name: Install Missing Libs
        run: |
          sudo apt-get update
          sudo apt-get install -y libxxf86vm1 libxrender1 libxtst6 libxi6 libglib2.0-0 libgtk-3-0 libasound2

      - name: Build with Maven
        run: mvn -B -ntp install -T 1C -DskipTests -o